services:
  app:

    build:
      dockerfile: ./Dockerfile
      context: ./
    # volumes:
    #   - static_volume:/code/static
    #   - media_volume:/code/media
    ports:
      - "127.0.0.1:${DB_PORT_OUT}:8000"
    depends_on:
      - pg
    command: 


  pg:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT_OUT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
  # static_volume:
  # media_volume: